### ISSUE TITLE
La consigna se cumple 

### ISSUE THREAD

**Issue by gastonorqueda** [pdepmartestm/bienvenida-2023-diegoc-c#1]
Algunas opiniones (personales) podes modificarlo o no, agregaria una descripcion un poco mas extensa. De que haces o que te gusta hacer. Para no dejar todo en un listado.

**Comment by diegoc-c** [comment]
Ahí le agregué un poco, no se me ocurren más cosas interesantes para ponerle. Gracias por tu opinión!
